version: '3'
services:
  api:
    image: openjdk:8u141-jdk
    working_dir: /opt/app
    ports:
      - "7316:7316"
    volumes:
      - ~/.aws:/root/.aws
      - ./api:/opt/app
    command: ./sbt -ivy /opt/app/.ivy2 ~reStart
  app:
    image: node:8.6.0-alpine
    working_dir: /opt/app
    ports:
      - "7315:7315"
    volumes:
      - ./app:/opt/app
    command: yarn run start
