#!/usr/bin/env bash

set -e

if [[ -n "${TRELLISCOPE_DEBUG}" ]]; then
    set -x
fi

function usage() {
    echo -n "Usage: $(basename "$0") [--native]
Starts servers using sbt and yarn

--native   Start server natively without Docker
"
}

if [ "${BASH_SOURCE[0]}" = "${0}" ]
then
    if [ "${1:-}" = "--help" ]
    then
        usage
    elif [ "${1:-}" = "--native" ]
    then
        (cd api && ./sbt ~reStart) &
        (cd app && yarn run start) &
        wait
    else
        docker-compose -f docker-compose.yml up
    fi
fi
