#!/usr/bin/env bash

set -e

if [[ -n "${TRELLISCOPE_DEBUG}" ]]; then
    set -x
fi

function usage() {
    echo -n "Usage: $(basename "$0") [--docker]
Starts servers using sbt and yarn

--docker   Start server inside a Docker container
"
}

if [ "${BASH_SOURCE[0]}" = "${0}" ]
then
    if [ "${1:-}" = "--help" ]
    then
        usage
    elif [ "${1:-}" = "--docker" ]
    then
        docker-compose -f docker-compose.yml up
    else
        (cd api && ./sbt ~reStart) &
        (cd app && yarn run start) &
        wait
    fi
fi
