#!/usr/bin/env bash

set -e

if [[ -n "${TRELLISCOPE_DEBUG}" ]]; then
    set -x
fi

function usage() {
    echo -n "Usage: $(basename "$0")
Builds and pulls container images using docker-compose.
"
}

if [ "${BASH_SOURCE[0]}" = "${0}" ]
then
    if [ "${1:-}" = "--help" ]
    then
        usage
    else
        # Install NPM modules
        docker-compose \
            -f docker-compose.yml \
            run --rm --no-deps app \
            yarn

        # Compile API
        docker-compose \
            -f docker-compose.yml \
            run --rm --no-deps api \
            ./sbt compile
    fi
fi
